sudo: false
language: generic
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - gcc-5
    - python-dev
    - python-pip
    - libdb++-dev
    - libdb-dev
    - libdb-java
    - libdb-java-dev
    - libdbus-glib-1-dev
    - libbluetooth-dev

cache:
  directories:
  - "$HOME/.gradle"

env:
  global:
  - CXX=g++-5
  - GCC_COMPILER=yes
  - MCPP_HOME=${TRAVIS_BUILD_DIR}/mcpp
  - OPTIMIZE=yes

before_install:
- git clone https://github.com/zeroc-ice/mcpp.git mcpp
- git submodule update --init

install:
- make -C ${MCPP_HOME} -j3
- make -C ice/cpp IceXML slice2java TestCommon -j3
- ice/java-compat/gradlew -p ice/java-compat Ice-compat:assemble
- make -j3

script:
- python allTests.py

notifications:
  email: travis-ci@zeroc.com
  slack:
    secure: cjBBFgPTmWKNzCjaLItWjN7oSp3j7emWw0/N2ZXcLZ1WBzIffuy6RtTf9+R8nwxEFABPlTRH6uRInDEIEN8GQ9hYZ0W36h8Fzp+2Z5rxX96RiC8Vgp3ti6T3y6yDspocce3v9wj1zLNoK2aMbifg7TUbUi+/NLACAv27nofOpQP5uP/TxJm21MsY3OZeX6Kxmdov47Z4km9y4DFwkSHfHv8VXqU55qTIO/bMm7BdsBtwidfomDo7vDy7UsfxzRi1ber+xWmcLGtQ+pfK9KptPdz+rf7anIF4yOE6REPpjeuYyTf/iMBGbTQh9eELJoZwVqNyz73iRi9EGTyfgvW3fhlN1U6sw76PqJtCHco+kzNF7bCzV1lv2mI8OwoWcvXQeWPlDceG4B4+bY8ZWG8Reg8PYQ9Vt3OcD3TKUXII3xX7U8KDsryN/hMjyn92vp2aBRyHNcEeCXlHxtpgYnl4dmkBTJjppl1BwPNEKyme6lyTn0XD2eRMw6W9l+N1bLR3qtDG3BADlPNWWlzgY6WLztIBfZYGeZVp1Yy6Cl3akHbjimRn10XAbtqpaCl+DAqsm0wXl2WWrJTLutlKfeDm6nWEXEYK5fY7AO12Ej8FX5HQd5DRtvcZ1VcplR2D10Rl5K+bJJBC8FvHMGYPAPH/yTErt68zSd0nXDzP22IP8jA=
